pub use substreams_ethereum_core::buffa;
pub use substreams_ethereum_core::scalar;
pub use substreams_ethereum_core::{
    abi, block_view, pb, rpc, Event, Function, LogLike, NULL_ADDRESS,
};
pub use substreams_ethereum_derive::EthabiContract;

// Those are dependencies that needs to be exported for `substreams-abigen` to work. Must not
// be removed.
pub use substreams_ethereum_core::IndexedDynamicValue;

/// Builder struct for generating type-safe bindings Rust code directly in your project from a contract's ABI.
/// This is equivalent to code generated by macro [use_contract].
///
/// # Example
///
/// Running the code below will generate a file called `erc721.rs` containing the
/// bindings inside, which exports an `erc` struct, along with all its events. Put into a
/// `build.rs` file this will generate the bindings during `cargo build`.
///
/// ```no_run
///     use anyhow::{Ok, Result};
///     use substreams_ethereum::Abigen;
///
///     fn main() -> Result<(), anyhow::Error> {
///         Abigen::new("ERC721", "abi/erc721.json")?
///             .generate()?
///             .write_to_file("src/abi/erc721.rs")?;
///
///         Ok(())
///     }
/// ```
pub use substreams_ethereum_abigen::build::Abigen;

/// This macro can be used to import an Ethereum ABI file in JSON format and generate all the
/// required bindings for ABI decoding/encoding in Rust, targetting `substreams` developer
/// experience. You prefer to have the code generated directly, check out [Abigen].
///
/// ```no_run
///     use substreams_ethereum::use_contract;
///
///     use_contract!(erc721, "./examples/abi/erc721.json");
/// ```
///
/// This invocation will generate the following code (signatures only for consiscness):
///
/// ```rust
/// mod erc721 {
///     pub mod events {
///         #[derive(Debug, Clone, PartialEq)]
///         pub struct Transfer {
///             pub from: Vec<u8>,
///             pub to: Vec<u8>,
///             pub token_id: substreams::scalar::BigInt,
///         }
///
///         impl Transfer {
///             pub fn match_log<L: substreams_ethereum::LogLike>(log: &L) -> bool {
///                // ...
///                # todo!()
///             }
///
///             pub fn decode<L: substreams_ethereum::LogLike>(log: &L) -> Result<Transfer, String> {
///                // ...
///                # todo!()
///             }
///         }
///
///         // ... Other events ...
///     }
/// }
/// ```
#[macro_export]
macro_rules! use_contract {
    ($module: ident, $path: expr) => {
        #[allow(dead_code)]
        #[allow(missing_docs)]
        #[allow(unused_imports)]
        #[allow(unused_mut)]
        #[allow(unused_variables)]
        pub mod $module {
            #[derive(substreams_ethereum::EthabiContract)]
            #[ethabi_contract_options(path = $path)]
            struct _Dummy;
        }
    };
}

/// Kept so a Substreams that calls it keeps compiling. Nothing here reaches for randomness
/// any more, so the macro expands to nothing and a `getrandom` dependency is no longer
/// needed in your `Cargo.toml`.
#[macro_export]
macro_rules! init {
    () => {};
}
