//! Protobuf types for the Substreams Ethereum block model.
//!
//! Generated by `buf generate`; see `buf.gen.yaml`.
//!
macro_rules! include_buffa {
    ($package:literal) => {
        include!(concat!($package, ".mod.rs"));
    };
}

/// Re-export the protobuf generated code directly, at some point we might
/// deprecate the `eth` module so `pb::eth::v2` becomes `pb::sf::ethereum::r#type::v2`.
pub mod sf {
    pub mod ethereum {
        pub mod r#type {
            pub mod v2 {
                include_buffa!("sf.ethereum.type.v2");
            }
        }

        pub mod substreams {
            pub mod v1 {
                include_buffa!("sf.ethereum.substreams.v1");
            }
        }
    }
}

pub mod eth {
    pub mod v2 {
        pub use crate::pb::sf::ethereum::r#type::v2::*;
    }
    pub mod rpc {
        pub use crate::pb::sf::ethereum::substreams::v1::*;
    }
}
