// @generated by buffa-codegen. DO NOT EDIT.

include!("sf.ethereum.type.v2.type.rs");
#[allow(
    non_camel_case_types,
    dead_code,
    unused_imports,
    unused_qualifications,
    clippy::derivable_impls,
    clippy::match_single_binding,
    clippy::uninlined_format_args,
    clippy::doc_lazy_continuation,
    clippy::module_inception
)]
pub mod __buffa {
    #[allow(unused_imports)]
    use super::*;
    pub mod view {
        #[allow(unused_imports)]
        use super::*;
        include!("sf.ethereum.type.v2.type.__view.rs");
    }
    pub mod lazy_view {
        #[allow(unused_imports)]
        use super::*;
        include!("sf.ethereum.type.v2.type.__lazy_view.rs");
    }
}
#[doc(inline)]
pub use self::__buffa::view::BlockView;
#[doc(inline)]
pub use self::__buffa::view::BlockOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::BlockLazyView;
#[doc(inline)]
pub use self::__buffa::view::BlockHeaderView;
#[doc(inline)]
pub use self::__buffa::view::BlockHeaderOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::BlockHeaderLazyView;
#[doc(inline)]
pub use self::__buffa::view::Uint64NestedArrayView;
#[doc(inline)]
pub use self::__buffa::view::Uint64NestedArrayOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::Uint64NestedArrayLazyView;
#[doc(inline)]
pub use self::__buffa::view::Uint64ArrayView;
#[doc(inline)]
pub use self::__buffa::view::Uint64ArrayOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::Uint64ArrayLazyView;
#[doc(inline)]
pub use self::__buffa::view::BigIntView;
#[doc(inline)]
pub use self::__buffa::view::BigIntOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::BigIntLazyView;
#[doc(inline)]
pub use self::__buffa::view::TransactionTraceView;
#[doc(inline)]
pub use self::__buffa::view::TransactionTraceOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::TransactionTraceLazyView;
#[doc(inline)]
pub use self::__buffa::view::AccessTupleView;
#[doc(inline)]
pub use self::__buffa::view::AccessTupleOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::AccessTupleLazyView;
#[doc(inline)]
pub use self::__buffa::view::SetCodeAuthorizationView;
#[doc(inline)]
pub use self::__buffa::view::SetCodeAuthorizationOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::SetCodeAuthorizationLazyView;
#[doc(inline)]
pub use self::__buffa::view::TransactionReceiptView;
#[doc(inline)]
pub use self::__buffa::view::TransactionReceiptOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::TransactionReceiptLazyView;
#[doc(inline)]
pub use self::__buffa::view::LogView;
#[doc(inline)]
pub use self::__buffa::view::LogOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::LogLazyView;
#[doc(inline)]
pub use self::__buffa::view::CallView;
#[doc(inline)]
pub use self::__buffa::view::CallOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::CallLazyView;
#[doc(inline)]
pub use self::__buffa::view::StorageChangeView;
#[doc(inline)]
pub use self::__buffa::view::StorageChangeOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::StorageChangeLazyView;
#[doc(inline)]
pub use self::__buffa::view::BalanceChangeView;
#[doc(inline)]
pub use self::__buffa::view::BalanceChangeOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::BalanceChangeLazyView;
#[doc(inline)]
pub use self::__buffa::view::NonceChangeView;
#[doc(inline)]
pub use self::__buffa::view::NonceChangeOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::NonceChangeLazyView;
#[doc(inline)]
pub use self::__buffa::view::AccountCreationView;
#[doc(inline)]
pub use self::__buffa::view::AccountCreationOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::AccountCreationLazyView;
#[doc(inline)]
pub use self::__buffa::view::CodeChangeView;
#[doc(inline)]
pub use self::__buffa::view::CodeChangeOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::CodeChangeLazyView;
#[doc(inline)]
pub use self::__buffa::view::GasChangeView;
#[doc(inline)]
pub use self::__buffa::view::GasChangeOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::GasChangeLazyView;
#[doc(inline)]
pub use self::__buffa::view::HeaderOnlyBlockView;
#[doc(inline)]
pub use self::__buffa::view::HeaderOnlyBlockOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::HeaderOnlyBlockLazyView;
#[doc(inline)]
pub use self::__buffa::view::BlockWithRefsView;
#[doc(inline)]
pub use self::__buffa::view::BlockWithRefsOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::BlockWithRefsLazyView;
#[doc(inline)]
pub use self::__buffa::view::TransactionTraceWithBlockRefView;
#[doc(inline)]
pub use self::__buffa::view::TransactionTraceWithBlockRefOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::TransactionTraceWithBlockRefLazyView;
#[doc(inline)]
pub use self::__buffa::view::TransactionRefsView;
#[doc(inline)]
pub use self::__buffa::view::TransactionRefsOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::TransactionRefsLazyView;
#[doc(inline)]
pub use self::__buffa::view::BlockRefView;
#[doc(inline)]
pub use self::__buffa::view::BlockRefOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::BlockRefLazyView;
#[doc(inline)]
pub use self::__buffa::view::WithdrawalView;
#[doc(inline)]
pub use self::__buffa::view::WithdrawalOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::WithdrawalLazyView;
#[doc(inline)]
pub use self::__buffa::view::BoolOptionalView;
#[doc(inline)]
pub use self::__buffa::view::BoolOptionalOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::BoolOptionalLazyView;
#[doc(inline)]
pub use self::__buffa::view::BoolRequiredView;
#[doc(inline)]
pub use self::__buffa::view::BoolRequiredOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::BoolRequiredLazyView;
