// @generated by buffa-codegen. DO NOT EDIT.

include!("sf.ethereum.substreams.v1.rpc.rs");
#[allow(
    non_camel_case_types,
    dead_code,
    unused_imports,
    unused_qualifications,
    clippy::derivable_impls,
    clippy::match_single_binding,
    clippy::uninlined_format_args,
    clippy::doc_lazy_continuation,
    clippy::module_inception
)]
pub mod __buffa {
    #[allow(unused_imports)]
    use super::*;
    pub mod view {
        #[allow(unused_imports)]
        use super::*;
        include!("sf.ethereum.substreams.v1.rpc.__view.rs");
    }
    pub mod lazy_view {
        #[allow(unused_imports)]
        use super::*;
        include!("sf.ethereum.substreams.v1.rpc.__lazy_view.rs");
    }
}
#[doc(inline)]
pub use self::__buffa::view::RpcCallsView;
#[doc(inline)]
pub use self::__buffa::view::RpcCallsOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::RpcCallsLazyView;
#[doc(inline)]
pub use self::__buffa::view::RpcCallView;
#[doc(inline)]
pub use self::__buffa::view::RpcCallOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::RpcCallLazyView;
#[doc(inline)]
pub use self::__buffa::view::RpcResponsesView;
#[doc(inline)]
pub use self::__buffa::view::RpcResponsesOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::RpcResponsesLazyView;
#[doc(inline)]
pub use self::__buffa::view::RpcResponseView;
#[doc(inline)]
pub use self::__buffa::view::RpcResponseOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::RpcResponseLazyView;
#[doc(inline)]
pub use self::__buffa::view::RpcGetBalanceRequestView;
#[doc(inline)]
pub use self::__buffa::view::RpcGetBalanceRequestOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::RpcGetBalanceRequestLazyView;
#[doc(inline)]
pub use self::__buffa::view::RpcGetBalanceResponseView;
#[doc(inline)]
pub use self::__buffa::view::RpcGetBalanceResponseOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::RpcGetBalanceResponseLazyView;
#[doc(inline)]
pub use self::__buffa::view::RpcGetBalanceRequestsView;
#[doc(inline)]
pub use self::__buffa::view::RpcGetBalanceRequestsOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::RpcGetBalanceRequestsLazyView;
#[doc(inline)]
pub use self::__buffa::view::RpcGetBalanceResponsesView;
#[doc(inline)]
pub use self::__buffa::view::RpcGetBalanceResponsesOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::RpcGetBalanceResponsesLazyView;
