// @generated by buffa-codegen. DO NOT EDIT.
// source: sf/ethereum/substreams/v1/rpc.proto

#[derive(Clone, Debug, Default)]
pub struct RpcCallsView<'a> {
    /// Field 1: `calls`
    pub calls: ::buffa::RepeatedView<'a, super::super::__buffa::view::RpcCallView<'a>>,
}
impl<'a> ::buffa::MessageView<'a> for RpcCallsView<'a> {
    type Owned = super::super::RpcCalls;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                ctx.register_element_memory(
                    ::core::mem::size_of::<super::super::__buffa::view::RpcCallView>(),
                )?;
                view.calls
                    .push(
                        <super::super::__buffa::view::RpcCallView as ::buffa::MessageView>::decode_view_ctx(
                            sub,
                            __sub_ctx,
                        )?,
                    );
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::RpcCalls, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::RpcCalls, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::RpcCalls {
            calls: self
                .calls
                .iter()
                .map(|v| v.to_owned_from_source(__buffa_src))
                .collect::<::core::result::Result<_, ::buffa::DecodeError>>()?,
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for RpcCallsView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        for v in &self.calls {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        for v in &self.calls {
            ::buffa::types::put_len_delimited_header(
                1u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
    }
}
impl<'a> ::buffa::MessageName for RpcCallsView<'a> {
    const PACKAGE: &'static str = "sf.ethereum.substreams.v1";
    const NAME: &'static str = "RpcCalls";
    const FULL_NAME: &'static str = "sf.ethereum.substreams.v1.RpcCalls";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.ethereum.substreams.v1.RpcCalls";
}
::buffa::impl_default_view_instance!(RpcCallsView);
::buffa::impl_view_reborrow!(RpcCallsView);
/** Self-contained, `'static` owned view of a `RpcCalls` message.

 Wraps [`::buffa::OwnedView`]`<`[`RpcCallsView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`RpcCallsView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct RpcCallsOwnedView(::buffa::OwnedView<RpcCallsView<'static>>);
impl RpcCallsOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(RpcCallsOwnedView(::buffa::OwnedView::decode(bytes)?))
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            RpcCallsOwnedView(::buffa::OwnedView::decode_with_options(bytes, opts)?),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::RpcCalls,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            RpcCallsOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`RpcCallsView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &RpcCallsView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::RpcCalls {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `calls`
    #[must_use]
    pub fn calls(
        &self,
    ) -> &::buffa::RepeatedView<'_, super::super::__buffa::view::RpcCallView<'_>> {
        &self.0.reborrow().calls
    }
}
impl ::core::convert::From<::buffa::OwnedView<RpcCallsView<'static>>>
for RpcCallsOwnedView {
    fn from(inner: ::buffa::OwnedView<RpcCallsView<'static>>) -> Self {
        RpcCallsOwnedView(inner)
    }
}
impl ::core::convert::From<RpcCallsOwnedView>
for ::buffa::OwnedView<RpcCallsView<'static>> {
    fn from(wrapper: RpcCallsOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<RpcCallsView<'static>>>
for RpcCallsOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<RpcCallsView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::RpcCalls {
    type View<'a> = RpcCallsView<'a>;
    type ViewHandle = RpcCallsOwnedView;
}
#[derive(Clone, Debug, Default)]
pub struct RpcCallView<'a> {
    /// Field 1: `to_addr`
    pub to_addr: &'a [u8],
    /// Field 2: `data`
    pub data: &'a [u8],
}
impl<'a> ::buffa::MessageView<'a> for RpcCallView<'a> {
    type Owned = super::super::RpcCall;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.to_addr = ::buffa::types::borrow_bytes(&mut cur)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.data = ::buffa::types::borrow_bytes(&mut cur)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::RpcCall, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::RpcCall, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::RpcCall {
            to_addr: (self.to_addr).to_vec(),
            data: (self.data).to_vec(),
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for RpcCallView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.to_addr.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.to_addr) as u64;
        }
        if !self.data.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.data) as u64;
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.to_addr.is_empty() {
            ::buffa::types::put_shared_bytes_field(1u32, &self.to_addr, buf);
        }
        if !self.data.is_empty() {
            ::buffa::types::put_shared_bytes_field(2u32, &self.data, buf);
        }
    }
}
impl<'a> ::buffa::MessageName for RpcCallView<'a> {
    const PACKAGE: &'static str = "sf.ethereum.substreams.v1";
    const NAME: &'static str = "RpcCall";
    const FULL_NAME: &'static str = "sf.ethereum.substreams.v1.RpcCall";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.ethereum.substreams.v1.RpcCall";
}
::buffa::impl_default_view_instance!(RpcCallView);
::buffa::impl_view_reborrow!(RpcCallView);
/** Self-contained, `'static` owned view of a `RpcCall` message.

 Wraps [`::buffa::OwnedView`]`<`[`RpcCallView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`RpcCallView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct RpcCallOwnedView(::buffa::OwnedView<RpcCallView<'static>>);
impl RpcCallOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(RpcCallOwnedView(::buffa::OwnedView::decode(bytes)?))
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            RpcCallOwnedView(::buffa::OwnedView::decode_with_options(bytes, opts)?),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::RpcCall,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            RpcCallOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`RpcCallView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &RpcCallView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::RpcCall {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `to_addr`
    #[must_use]
    pub fn to_addr(&self) -> &'_ [u8] {
        self.0.reborrow().to_addr
    }
    /// Field 2: `data`
    #[must_use]
    pub fn data(&self) -> &'_ [u8] {
        self.0.reborrow().data
    }
}
impl ::core::convert::From<::buffa::OwnedView<RpcCallView<'static>>>
for RpcCallOwnedView {
    fn from(inner: ::buffa::OwnedView<RpcCallView<'static>>) -> Self {
        RpcCallOwnedView(inner)
    }
}
impl ::core::convert::From<RpcCallOwnedView>
for ::buffa::OwnedView<RpcCallView<'static>> {
    fn from(wrapper: RpcCallOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<RpcCallView<'static>>>
for RpcCallOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<RpcCallView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::RpcCall {
    type View<'a> = RpcCallView<'a>;
    type ViewHandle = RpcCallOwnedView;
}
#[derive(Clone, Debug, Default)]
pub struct RpcResponsesView<'a> {
    /// Field 1: `responses`
    pub responses: ::buffa::RepeatedView<
        'a,
        super::super::__buffa::view::RpcResponseView<'a>,
    >,
}
impl<'a> ::buffa::MessageView<'a> for RpcResponsesView<'a> {
    type Owned = super::super::RpcResponses;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                ctx.register_element_memory(
                    ::core::mem::size_of::<
                        super::super::__buffa::view::RpcResponseView,
                    >(),
                )?;
                view.responses
                    .push(
                        <super::super::__buffa::view::RpcResponseView as ::buffa::MessageView>::decode_view_ctx(
                            sub,
                            __sub_ctx,
                        )?,
                    );
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::RpcResponses, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::RpcResponses, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::RpcResponses {
            responses: self
                .responses
                .iter()
                .map(|v| v.to_owned_from_source(__buffa_src))
                .collect::<::core::result::Result<_, ::buffa::DecodeError>>()?,
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for RpcResponsesView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        for v in &self.responses {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        for v in &self.responses {
            ::buffa::types::put_len_delimited_header(
                1u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
    }
}
impl<'a> ::buffa::MessageName for RpcResponsesView<'a> {
    const PACKAGE: &'static str = "sf.ethereum.substreams.v1";
    const NAME: &'static str = "RpcResponses";
    const FULL_NAME: &'static str = "sf.ethereum.substreams.v1.RpcResponses";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.ethereum.substreams.v1.RpcResponses";
}
::buffa::impl_default_view_instance!(RpcResponsesView);
::buffa::impl_view_reborrow!(RpcResponsesView);
/** Self-contained, `'static` owned view of a `RpcResponses` message.

 Wraps [`::buffa::OwnedView`]`<`[`RpcResponsesView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`RpcResponsesView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct RpcResponsesOwnedView(::buffa::OwnedView<RpcResponsesView<'static>>);
impl RpcResponsesOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            RpcResponsesOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            RpcResponsesOwnedView(::buffa::OwnedView::decode_with_options(bytes, opts)?),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::RpcResponses,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            RpcResponsesOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`RpcResponsesView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &RpcResponsesView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::RpcResponses {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `responses`
    #[must_use]
    pub fn responses(
        &self,
    ) -> &::buffa::RepeatedView<'_, super::super::__buffa::view::RpcResponseView<'_>> {
        &self.0.reborrow().responses
    }
}
impl ::core::convert::From<::buffa::OwnedView<RpcResponsesView<'static>>>
for RpcResponsesOwnedView {
    fn from(inner: ::buffa::OwnedView<RpcResponsesView<'static>>) -> Self {
        RpcResponsesOwnedView(inner)
    }
}
impl ::core::convert::From<RpcResponsesOwnedView>
for ::buffa::OwnedView<RpcResponsesView<'static>> {
    fn from(wrapper: RpcResponsesOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<RpcResponsesView<'static>>>
for RpcResponsesOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<RpcResponsesView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::RpcResponses {
    type View<'a> = RpcResponsesView<'a>;
    type ViewHandle = RpcResponsesOwnedView;
}
#[derive(Clone, Debug, Default)]
pub struct RpcResponseView<'a> {
    /// Field 1: `raw`
    pub raw: &'a [u8],
    /// Field 2: `failed`
    pub failed: bool,
}
impl<'a> ::buffa::MessageView<'a> for RpcResponseView<'a> {
    type Owned = super::super::RpcResponse;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.raw = ::buffa::types::borrow_bytes(&mut cur)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.failed = ::buffa::types::decode_bool(&mut cur)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::RpcResponse, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::RpcResponse, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::RpcResponse {
            raw: (self.raw).to_vec(),
            failed: self.failed,
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for RpcResponseView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.raw.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.raw) as u64;
        }
        if self.failed {
            size += 1u64 + ::buffa::types::BOOL_ENCODED_LEN as u64;
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.raw.is_empty() {
            ::buffa::types::put_shared_bytes_field(1u32, &self.raw, buf);
        }
        if self.failed {
            ::buffa::types::put_bool_field(2u32, self.failed, buf);
        }
    }
}
impl<'a> ::buffa::MessageName for RpcResponseView<'a> {
    const PACKAGE: &'static str = "sf.ethereum.substreams.v1";
    const NAME: &'static str = "RpcResponse";
    const FULL_NAME: &'static str = "sf.ethereum.substreams.v1.RpcResponse";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.ethereum.substreams.v1.RpcResponse";
}
::buffa::impl_default_view_instance!(RpcResponseView);
::buffa::impl_view_reborrow!(RpcResponseView);
/** Self-contained, `'static` owned view of a `RpcResponse` message.

 Wraps [`::buffa::OwnedView`]`<`[`RpcResponseView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`RpcResponseView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct RpcResponseOwnedView(::buffa::OwnedView<RpcResponseView<'static>>);
impl RpcResponseOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            RpcResponseOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            RpcResponseOwnedView(::buffa::OwnedView::decode_with_options(bytes, opts)?),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::RpcResponse,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            RpcResponseOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`RpcResponseView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &RpcResponseView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::RpcResponse {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `raw`
    #[must_use]
    pub fn raw(&self) -> &'_ [u8] {
        self.0.reborrow().raw
    }
    /// Field 2: `failed`
    #[must_use]
    pub fn failed(&self) -> bool {
        self.0.reborrow().failed
    }
}
impl ::core::convert::From<::buffa::OwnedView<RpcResponseView<'static>>>
for RpcResponseOwnedView {
    fn from(inner: ::buffa::OwnedView<RpcResponseView<'static>>) -> Self {
        RpcResponseOwnedView(inner)
    }
}
impl ::core::convert::From<RpcResponseOwnedView>
for ::buffa::OwnedView<RpcResponseView<'static>> {
    fn from(wrapper: RpcResponseOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<RpcResponseView<'static>>>
for RpcResponseOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<RpcResponseView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::RpcResponse {
    type View<'a> = RpcResponseView<'a>;
    type ViewHandle = RpcResponseOwnedView;
}
#[derive(Clone, Debug, Default)]
pub struct RpcGetBalanceRequestView<'a> {
    /// Field 1: `address`
    pub address: &'a [u8],
    /// Field 2: `block`
    pub block: &'a str,
}
impl<'a> ::buffa::MessageView<'a> for RpcGetBalanceRequestView<'a> {
    type Owned = super::super::RpcGetBalanceRequest;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.address = ::buffa::types::borrow_bytes(&mut cur)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.block = ::buffa::types::borrow_str(&mut cur)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<
        super::super::RpcGetBalanceRequest,
        ::buffa::DecodeError,
    > {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<
        super::super::RpcGetBalanceRequest,
        ::buffa::DecodeError,
    > {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::RpcGetBalanceRequest {
            address: (self.address).to_vec(),
            block: self.block.to_string(),
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for RpcGetBalanceRequestView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.address.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.address) as u64;
        }
        if !self.block.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.block) as u64;
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.address.is_empty() {
            ::buffa::types::put_shared_bytes_field(1u32, &self.address, buf);
        }
        if !self.block.is_empty() {
            ::buffa::types::put_string_field(2u32, &self.block, buf);
        }
    }
}
impl<'a> ::buffa::MessageName for RpcGetBalanceRequestView<'a> {
    const PACKAGE: &'static str = "sf.ethereum.substreams.v1";
    const NAME: &'static str = "RpcGetBalanceRequest";
    const FULL_NAME: &'static str = "sf.ethereum.substreams.v1.RpcGetBalanceRequest";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.ethereum.substreams.v1.RpcGetBalanceRequest";
}
::buffa::impl_default_view_instance!(RpcGetBalanceRequestView);
::buffa::impl_view_reborrow!(RpcGetBalanceRequestView);
/** Self-contained, `'static` owned view of a `RpcGetBalanceRequest` message.

 Wraps [`::buffa::OwnedView`]`<`[`RpcGetBalanceRequestView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`RpcGetBalanceRequestView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct RpcGetBalanceRequestOwnedView(
    ::buffa::OwnedView<RpcGetBalanceRequestView<'static>>,
);
impl RpcGetBalanceRequestOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            RpcGetBalanceRequestOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            RpcGetBalanceRequestOwnedView(
                ::buffa::OwnedView::decode_with_options(bytes, opts)?,
            ),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::RpcGetBalanceRequest,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            RpcGetBalanceRequestOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`RpcGetBalanceRequestView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &RpcGetBalanceRequestView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::RpcGetBalanceRequest {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `address`
    #[must_use]
    pub fn address(&self) -> &'_ [u8] {
        self.0.reborrow().address
    }
    /// Field 2: `block`
    #[must_use]
    pub fn block(&self) -> &'_ str {
        self.0.reborrow().block
    }
}
impl ::core::convert::From<::buffa::OwnedView<RpcGetBalanceRequestView<'static>>>
for RpcGetBalanceRequestOwnedView {
    fn from(inner: ::buffa::OwnedView<RpcGetBalanceRequestView<'static>>) -> Self {
        RpcGetBalanceRequestOwnedView(inner)
    }
}
impl ::core::convert::From<RpcGetBalanceRequestOwnedView>
for ::buffa::OwnedView<RpcGetBalanceRequestView<'static>> {
    fn from(wrapper: RpcGetBalanceRequestOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<RpcGetBalanceRequestView<'static>>>
for RpcGetBalanceRequestOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<RpcGetBalanceRequestView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::RpcGetBalanceRequest {
    type View<'a> = RpcGetBalanceRequestView<'a>;
    type ViewHandle = RpcGetBalanceRequestOwnedView;
}
#[derive(Clone, Debug, Default)]
pub struct RpcGetBalanceResponseView<'a> {
    /// Field 1: `balance`
    pub balance: &'a [u8],
    /// Field 2: `failed`
    pub failed: bool,
}
impl<'a> ::buffa::MessageView<'a> for RpcGetBalanceResponseView<'a> {
    type Owned = super::super::RpcGetBalanceResponse;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.balance = ::buffa::types::borrow_bytes(&mut cur)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.failed = ::buffa::types::decode_bool(&mut cur)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<
        super::super::RpcGetBalanceResponse,
        ::buffa::DecodeError,
    > {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<
        super::super::RpcGetBalanceResponse,
        ::buffa::DecodeError,
    > {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::RpcGetBalanceResponse {
            balance: (self.balance).to_vec(),
            failed: self.failed,
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for RpcGetBalanceResponseView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.balance.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.balance) as u64;
        }
        if self.failed {
            size += 1u64 + ::buffa::types::BOOL_ENCODED_LEN as u64;
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.balance.is_empty() {
            ::buffa::types::put_shared_bytes_field(1u32, &self.balance, buf);
        }
        if self.failed {
            ::buffa::types::put_bool_field(2u32, self.failed, buf);
        }
    }
}
impl<'a> ::buffa::MessageName for RpcGetBalanceResponseView<'a> {
    const PACKAGE: &'static str = "sf.ethereum.substreams.v1";
    const NAME: &'static str = "RpcGetBalanceResponse";
    const FULL_NAME: &'static str = "sf.ethereum.substreams.v1.RpcGetBalanceResponse";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.ethereum.substreams.v1.RpcGetBalanceResponse";
}
::buffa::impl_default_view_instance!(RpcGetBalanceResponseView);
::buffa::impl_view_reborrow!(RpcGetBalanceResponseView);
/** Self-contained, `'static` owned view of a `RpcGetBalanceResponse` message.

 Wraps [`::buffa::OwnedView`]`<`[`RpcGetBalanceResponseView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`RpcGetBalanceResponseView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct RpcGetBalanceResponseOwnedView(
    ::buffa::OwnedView<RpcGetBalanceResponseView<'static>>,
);
impl RpcGetBalanceResponseOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            RpcGetBalanceResponseOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            RpcGetBalanceResponseOwnedView(
                ::buffa::OwnedView::decode_with_options(bytes, opts)?,
            ),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::RpcGetBalanceResponse,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            RpcGetBalanceResponseOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`RpcGetBalanceResponseView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &RpcGetBalanceResponseView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::RpcGetBalanceResponse {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `balance`
    #[must_use]
    pub fn balance(&self) -> &'_ [u8] {
        self.0.reborrow().balance
    }
    /// Field 2: `failed`
    #[must_use]
    pub fn failed(&self) -> bool {
        self.0.reborrow().failed
    }
}
impl ::core::convert::From<::buffa::OwnedView<RpcGetBalanceResponseView<'static>>>
for RpcGetBalanceResponseOwnedView {
    fn from(inner: ::buffa::OwnedView<RpcGetBalanceResponseView<'static>>) -> Self {
        RpcGetBalanceResponseOwnedView(inner)
    }
}
impl ::core::convert::From<RpcGetBalanceResponseOwnedView>
for ::buffa::OwnedView<RpcGetBalanceResponseView<'static>> {
    fn from(wrapper: RpcGetBalanceResponseOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<RpcGetBalanceResponseView<'static>>>
for RpcGetBalanceResponseOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<RpcGetBalanceResponseView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::RpcGetBalanceResponse {
    type View<'a> = RpcGetBalanceResponseView<'a>;
    type ViewHandle = RpcGetBalanceResponseOwnedView;
}
#[derive(Clone, Debug, Default)]
pub struct RpcGetBalanceRequestsView<'a> {
    /// Field 1: `requests`
    pub requests: ::buffa::RepeatedView<
        'a,
        super::super::__buffa::view::RpcGetBalanceRequestView<'a>,
    >,
}
impl<'a> ::buffa::MessageView<'a> for RpcGetBalanceRequestsView<'a> {
    type Owned = super::super::RpcGetBalanceRequests;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                ctx.register_element_memory(
                    ::core::mem::size_of::<
                        super::super::__buffa::view::RpcGetBalanceRequestView,
                    >(),
                )?;
                view.requests
                    .push(
                        <super::super::__buffa::view::RpcGetBalanceRequestView as ::buffa::MessageView>::decode_view_ctx(
                            sub,
                            __sub_ctx,
                        )?,
                    );
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<
        super::super::RpcGetBalanceRequests,
        ::buffa::DecodeError,
    > {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<
        super::super::RpcGetBalanceRequests,
        ::buffa::DecodeError,
    > {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::RpcGetBalanceRequests {
            requests: self
                .requests
                .iter()
                .map(|v| v.to_owned_from_source(__buffa_src))
                .collect::<::core::result::Result<_, ::buffa::DecodeError>>()?,
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for RpcGetBalanceRequestsView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        for v in &self.requests {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        for v in &self.requests {
            ::buffa::types::put_len_delimited_header(
                1u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
    }
}
impl<'a> ::buffa::MessageName for RpcGetBalanceRequestsView<'a> {
    const PACKAGE: &'static str = "sf.ethereum.substreams.v1";
    const NAME: &'static str = "RpcGetBalanceRequests";
    const FULL_NAME: &'static str = "sf.ethereum.substreams.v1.RpcGetBalanceRequests";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.ethereum.substreams.v1.RpcGetBalanceRequests";
}
::buffa::impl_default_view_instance!(RpcGetBalanceRequestsView);
::buffa::impl_view_reborrow!(RpcGetBalanceRequestsView);
/** Self-contained, `'static` owned view of a `RpcGetBalanceRequests` message.

 Wraps [`::buffa::OwnedView`]`<`[`RpcGetBalanceRequestsView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`RpcGetBalanceRequestsView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct RpcGetBalanceRequestsOwnedView(
    ::buffa::OwnedView<RpcGetBalanceRequestsView<'static>>,
);
impl RpcGetBalanceRequestsOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            RpcGetBalanceRequestsOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            RpcGetBalanceRequestsOwnedView(
                ::buffa::OwnedView::decode_with_options(bytes, opts)?,
            ),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::RpcGetBalanceRequests,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            RpcGetBalanceRequestsOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`RpcGetBalanceRequestsView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &RpcGetBalanceRequestsView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::RpcGetBalanceRequests {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `requests`
    #[must_use]
    pub fn requests(
        &self,
    ) -> &::buffa::RepeatedView<
        '_,
        super::super::__buffa::view::RpcGetBalanceRequestView<'_>,
    > {
        &self.0.reborrow().requests
    }
}
impl ::core::convert::From<::buffa::OwnedView<RpcGetBalanceRequestsView<'static>>>
for RpcGetBalanceRequestsOwnedView {
    fn from(inner: ::buffa::OwnedView<RpcGetBalanceRequestsView<'static>>) -> Self {
        RpcGetBalanceRequestsOwnedView(inner)
    }
}
impl ::core::convert::From<RpcGetBalanceRequestsOwnedView>
for ::buffa::OwnedView<RpcGetBalanceRequestsView<'static>> {
    fn from(wrapper: RpcGetBalanceRequestsOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<RpcGetBalanceRequestsView<'static>>>
for RpcGetBalanceRequestsOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<RpcGetBalanceRequestsView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::RpcGetBalanceRequests {
    type View<'a> = RpcGetBalanceRequestsView<'a>;
    type ViewHandle = RpcGetBalanceRequestsOwnedView;
}
#[derive(Clone, Debug, Default)]
pub struct RpcGetBalanceResponsesView<'a> {
    /// Field 1: `responses`
    pub responses: ::buffa::RepeatedView<
        'a,
        super::super::__buffa::view::RpcGetBalanceResponseView<'a>,
    >,
}
impl<'a> ::buffa::MessageView<'a> for RpcGetBalanceResponsesView<'a> {
    type Owned = super::super::RpcGetBalanceResponses;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                ctx.register_element_memory(
                    ::core::mem::size_of::<
                        super::super::__buffa::view::RpcGetBalanceResponseView,
                    >(),
                )?;
                view.responses
                    .push(
                        <super::super::__buffa::view::RpcGetBalanceResponseView as ::buffa::MessageView>::decode_view_ctx(
                            sub,
                            __sub_ctx,
                        )?,
                    );
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<
        super::super::RpcGetBalanceResponses,
        ::buffa::DecodeError,
    > {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<
        super::super::RpcGetBalanceResponses,
        ::buffa::DecodeError,
    > {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::RpcGetBalanceResponses {
            responses: self
                .responses
                .iter()
                .map(|v| v.to_owned_from_source(__buffa_src))
                .collect::<::core::result::Result<_, ::buffa::DecodeError>>()?,
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for RpcGetBalanceResponsesView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        for v in &self.responses {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        for v in &self.responses {
            ::buffa::types::put_len_delimited_header(
                1u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
    }
}
impl<'a> ::buffa::MessageName for RpcGetBalanceResponsesView<'a> {
    const PACKAGE: &'static str = "sf.ethereum.substreams.v1";
    const NAME: &'static str = "RpcGetBalanceResponses";
    const FULL_NAME: &'static str = "sf.ethereum.substreams.v1.RpcGetBalanceResponses";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.ethereum.substreams.v1.RpcGetBalanceResponses";
}
::buffa::impl_default_view_instance!(RpcGetBalanceResponsesView);
::buffa::impl_view_reborrow!(RpcGetBalanceResponsesView);
/** Self-contained, `'static` owned view of a `RpcGetBalanceResponses` message.

 Wraps [`::buffa::OwnedView`]`<`[`RpcGetBalanceResponsesView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`RpcGetBalanceResponsesView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct RpcGetBalanceResponsesOwnedView(
    ::buffa::OwnedView<RpcGetBalanceResponsesView<'static>>,
);
impl RpcGetBalanceResponsesOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            RpcGetBalanceResponsesOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            RpcGetBalanceResponsesOwnedView(
                ::buffa::OwnedView::decode_with_options(bytes, opts)?,
            ),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::RpcGetBalanceResponses,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            RpcGetBalanceResponsesOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`RpcGetBalanceResponsesView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &RpcGetBalanceResponsesView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::RpcGetBalanceResponses {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `responses`
    #[must_use]
    pub fn responses(
        &self,
    ) -> &::buffa::RepeatedView<
        '_,
        super::super::__buffa::view::RpcGetBalanceResponseView<'_>,
    > {
        &self.0.reborrow().responses
    }
}
impl ::core::convert::From<::buffa::OwnedView<RpcGetBalanceResponsesView<'static>>>
for RpcGetBalanceResponsesOwnedView {
    fn from(inner: ::buffa::OwnedView<RpcGetBalanceResponsesView<'static>>) -> Self {
        RpcGetBalanceResponsesOwnedView(inner)
    }
}
impl ::core::convert::From<RpcGetBalanceResponsesOwnedView>
for ::buffa::OwnedView<RpcGetBalanceResponsesView<'static>> {
    fn from(wrapper: RpcGetBalanceResponsesOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<RpcGetBalanceResponsesView<'static>>>
for RpcGetBalanceResponsesOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<RpcGetBalanceResponsesView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::RpcGetBalanceResponses {
    type View<'a> = RpcGetBalanceResponsesView<'a>;
    type ViewHandle = RpcGetBalanceResponsesOwnedView;
}
