// @generated by buffa-codegen. DO NOT EDIT.
// source: sf/ethereum/substreams/v1/rpc.proto

#[derive(Clone, PartialEq, Default)]
pub struct RpcCalls {
    /// Field 1: `calls`
    pub calls: ::buffa::alloc::vec::Vec<RpcCall>,
}
impl ::core::fmt::Debug for RpcCalls {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("RpcCalls").field("calls", &self.calls).finish()
    }
}
impl RpcCalls {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/sf.ethereum.substreams.v1.RpcCalls";
}
::buffa::impl_default_instance!(RpcCalls);
impl ::buffa::MessageName for RpcCalls {
    const PACKAGE: &'static str = "sf.ethereum.substreams.v1";
    const NAME: &'static str = "RpcCalls";
    const FULL_NAME: &'static str = "sf.ethereum.substreams.v1.RpcCalls";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.ethereum.substreams.v1.RpcCalls";
}
impl ::buffa::Message for RpcCalls {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        for v in &self.calls {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        for v in &self.calls {
            ::buffa::types::put_len_delimited_header(
                1u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let mut elem = ::core::default::Default::default();
                ctx.register_element_memory(
                    ::buffa::__private::element_footprint(&elem),
                )?;
                ::buffa::Message::merge_length_delimited(&mut elem, buf, ctx)?;
                self.calls.push(elem);
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.calls.clear();
    }
}
#[derive(Clone, PartialEq, Default)]
pub struct RpcCall {
    /// Field 1: `to_addr`
    pub to_addr: ::buffa::alloc::vec::Vec<u8>,
    /// Field 2: `data`
    pub data: ::buffa::alloc::vec::Vec<u8>,
}
impl ::core::fmt::Debug for RpcCall {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("RpcCall")
            .field("to_addr", &self.to_addr)
            .field("data", &self.data)
            .finish()
    }
}
impl RpcCall {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/sf.ethereum.substreams.v1.RpcCall";
}
::buffa::impl_default_instance!(RpcCall);
impl ::buffa::MessageName for RpcCall {
    const PACKAGE: &'static str = "sf.ethereum.substreams.v1";
    const NAME: &'static str = "RpcCall";
    const FULL_NAME: &'static str = "sf.ethereum.substreams.v1.RpcCall";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.ethereum.substreams.v1.RpcCall";
}
impl ::buffa::Message for RpcCall {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.to_addr.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.to_addr) as u64;
        }
        if !self.data.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.data) as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.to_addr.is_empty() {
            ::buffa::types::put_shared_bytes_field(1u32, &self.to_addr, buf);
        }
        if !self.data.is_empty() {
            ::buffa::types::put_shared_bytes_field(2u32, &self.data, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_bytes(&mut self.to_addr, buf)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_bytes(&mut self.data, buf)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.to_addr.clear();
        self.data.clear();
    }
}
#[derive(Clone, PartialEq, Default)]
pub struct RpcResponses {
    /// Field 1: `responses`
    pub responses: ::buffa::alloc::vec::Vec<RpcResponse>,
}
impl ::core::fmt::Debug for RpcResponses {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("RpcResponses").field("responses", &self.responses).finish()
    }
}
impl RpcResponses {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/sf.ethereum.substreams.v1.RpcResponses";
}
::buffa::impl_default_instance!(RpcResponses);
impl ::buffa::MessageName for RpcResponses {
    const PACKAGE: &'static str = "sf.ethereum.substreams.v1";
    const NAME: &'static str = "RpcResponses";
    const FULL_NAME: &'static str = "sf.ethereum.substreams.v1.RpcResponses";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.ethereum.substreams.v1.RpcResponses";
}
impl ::buffa::Message for RpcResponses {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        for v in &self.responses {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        for v in &self.responses {
            ::buffa::types::put_len_delimited_header(
                1u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let mut elem = ::core::default::Default::default();
                ctx.register_element_memory(
                    ::buffa::__private::element_footprint(&elem),
                )?;
                ::buffa::Message::merge_length_delimited(&mut elem, buf, ctx)?;
                self.responses.push(elem);
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.responses.clear();
    }
}
#[derive(Clone, PartialEq, Default)]
pub struct RpcResponse {
    /// Field 1: `raw`
    pub raw: ::buffa::alloc::vec::Vec<u8>,
    /// Field 2: `failed`
    pub failed: bool,
}
impl ::core::fmt::Debug for RpcResponse {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("RpcResponse")
            .field("raw", &self.raw)
            .field("failed", &self.failed)
            .finish()
    }
}
impl RpcResponse {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/sf.ethereum.substreams.v1.RpcResponse";
}
::buffa::impl_default_instance!(RpcResponse);
impl ::buffa::MessageName for RpcResponse {
    const PACKAGE: &'static str = "sf.ethereum.substreams.v1";
    const NAME: &'static str = "RpcResponse";
    const FULL_NAME: &'static str = "sf.ethereum.substreams.v1.RpcResponse";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.ethereum.substreams.v1.RpcResponse";
}
impl ::buffa::Message for RpcResponse {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.raw.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.raw) as u64;
        }
        if self.failed {
            size += 1u64 + ::buffa::types::BOOL_ENCODED_LEN as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.raw.is_empty() {
            ::buffa::types::put_shared_bytes_field(1u32, &self.raw, buf);
        }
        if self.failed {
            ::buffa::types::put_bool_field(2u32, self.failed, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_bytes(&mut self.raw, buf)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.failed = ::buffa::types::decode_bool(buf)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.raw.clear();
        self.failed = false;
    }
}
#[derive(Clone, PartialEq, Default)]
pub struct RpcGetBalanceRequest {
    /// Field 1: `address`
    pub address: ::buffa::alloc::vec::Vec<u8>,
    /// Field 2: `block`
    pub block: ::buffa::alloc::string::String,
}
impl ::core::fmt::Debug for RpcGetBalanceRequest {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("RpcGetBalanceRequest")
            .field("address", &self.address)
            .field("block", &self.block)
            .finish()
    }
}
impl RpcGetBalanceRequest {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/sf.ethereum.substreams.v1.RpcGetBalanceRequest";
}
::buffa::impl_default_instance!(RpcGetBalanceRequest);
impl ::buffa::MessageName for RpcGetBalanceRequest {
    const PACKAGE: &'static str = "sf.ethereum.substreams.v1";
    const NAME: &'static str = "RpcGetBalanceRequest";
    const FULL_NAME: &'static str = "sf.ethereum.substreams.v1.RpcGetBalanceRequest";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.ethereum.substreams.v1.RpcGetBalanceRequest";
}
impl ::buffa::Message for RpcGetBalanceRequest {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.address.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.address) as u64;
        }
        if !self.block.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.block) as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.address.is_empty() {
            ::buffa::types::put_shared_bytes_field(1u32, &self.address, buf);
        }
        if !self.block.is_empty() {
            ::buffa::types::put_string_field(2u32, &self.block, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_bytes(&mut self.address, buf)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.block, buf)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.address.clear();
        self.block.clear();
    }
}
#[derive(Clone, PartialEq, Default)]
pub struct RpcGetBalanceResponse {
    /// Field 1: `balance`
    pub balance: ::buffa::alloc::vec::Vec<u8>,
    /// Field 2: `failed`
    pub failed: bool,
}
impl ::core::fmt::Debug for RpcGetBalanceResponse {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("RpcGetBalanceResponse")
            .field("balance", &self.balance)
            .field("failed", &self.failed)
            .finish()
    }
}
impl RpcGetBalanceResponse {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/sf.ethereum.substreams.v1.RpcGetBalanceResponse";
}
::buffa::impl_default_instance!(RpcGetBalanceResponse);
impl ::buffa::MessageName for RpcGetBalanceResponse {
    const PACKAGE: &'static str = "sf.ethereum.substreams.v1";
    const NAME: &'static str = "RpcGetBalanceResponse";
    const FULL_NAME: &'static str = "sf.ethereum.substreams.v1.RpcGetBalanceResponse";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.ethereum.substreams.v1.RpcGetBalanceResponse";
}
impl ::buffa::Message for RpcGetBalanceResponse {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.balance.is_empty() {
            size += 1u64 + ::buffa::types::bytes_encoded_len(&self.balance) as u64;
        }
        if self.failed {
            size += 1u64 + ::buffa::types::BOOL_ENCODED_LEN as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.balance.is_empty() {
            ::buffa::types::put_shared_bytes_field(1u32, &self.balance, buf);
        }
        if self.failed {
            ::buffa::types::put_bool_field(2u32, self.failed, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_bytes(&mut self.balance, buf)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.failed = ::buffa::types::decode_bool(buf)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.balance.clear();
        self.failed = false;
    }
}
#[derive(Clone, PartialEq, Default)]
pub struct RpcGetBalanceRequests {
    /// Field 1: `requests`
    pub requests: ::buffa::alloc::vec::Vec<RpcGetBalanceRequest>,
}
impl ::core::fmt::Debug for RpcGetBalanceRequests {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("RpcGetBalanceRequests")
            .field("requests", &self.requests)
            .finish()
    }
}
impl RpcGetBalanceRequests {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/sf.ethereum.substreams.v1.RpcGetBalanceRequests";
}
::buffa::impl_default_instance!(RpcGetBalanceRequests);
impl ::buffa::MessageName for RpcGetBalanceRequests {
    const PACKAGE: &'static str = "sf.ethereum.substreams.v1";
    const NAME: &'static str = "RpcGetBalanceRequests";
    const FULL_NAME: &'static str = "sf.ethereum.substreams.v1.RpcGetBalanceRequests";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.ethereum.substreams.v1.RpcGetBalanceRequests";
}
impl ::buffa::Message for RpcGetBalanceRequests {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        for v in &self.requests {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        for v in &self.requests {
            ::buffa::types::put_len_delimited_header(
                1u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let mut elem = ::core::default::Default::default();
                ctx.register_element_memory(
                    ::buffa::__private::element_footprint(&elem),
                )?;
                ::buffa::Message::merge_length_delimited(&mut elem, buf, ctx)?;
                self.requests.push(elem);
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.requests.clear();
    }
}
#[derive(Clone, PartialEq, Default)]
pub struct RpcGetBalanceResponses {
    /// Field 1: `responses`
    pub responses: ::buffa::alloc::vec::Vec<RpcGetBalanceResponse>,
}
impl ::core::fmt::Debug for RpcGetBalanceResponses {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("RpcGetBalanceResponses")
            .field("responses", &self.responses)
            .finish()
    }
}
impl RpcGetBalanceResponses {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/sf.ethereum.substreams.v1.RpcGetBalanceResponses";
}
::buffa::impl_default_instance!(RpcGetBalanceResponses);
impl ::buffa::MessageName for RpcGetBalanceResponses {
    const PACKAGE: &'static str = "sf.ethereum.substreams.v1";
    const NAME: &'static str = "RpcGetBalanceResponses";
    const FULL_NAME: &'static str = "sf.ethereum.substreams.v1.RpcGetBalanceResponses";
    const TYPE_URL: &'static str = "type.googleapis.com/sf.ethereum.substreams.v1.RpcGetBalanceResponses";
}
impl ::buffa::Message for RpcGetBalanceResponses {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        for v in &self.responses {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        for v in &self.responses {
            ::buffa::types::put_len_delimited_header(
                1u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let mut elem = ::core::default::Default::default();
                ctx.register_element_memory(
                    ::buffa::__private::element_footprint(&elem),
                )?;
                ::buffa::Message::merge_length_delimited(&mut elem, buf, ctx)?;
                self.responses.push(elem);
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.responses.clear();
    }
}
