name: Continuous Integration

on:
  push:
    branches: [master, develop, feature/test-new-gh-actions]
  pull_request:
    types: [opened, synchronize, reopened]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  rustfmt:
    name: Check rustfmt style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Rust Toolchain(s)
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Check formatting
        run: |
          cargo fmt --all -- --check
        env:
          RUSTFLAGS: "-D warnings"

      - name: Run tests
        run: |
          cargo test --release --target x86_64-unknown-linux-gnu --lib --bins --tests
        env:
          RUSTFLAGS: "-D warnings"

      - name: Build
        run: |
          cargo build --release --target wasm32-unknown-unknown
        env:
          RUSTFLAGS: "-D warnings"